/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.arunkumar.lynket.buildplugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import java.util.*

class BuildPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        project.publishLocalProperties()
    }


    private fun Project.publishLocalProperties() {
        val localPropertiesFile = rootProject.file("local.properties")
        if (localPropertiesFile.exists()) {
            val localProperties = Properties().apply { load(localPropertiesFile.bufferedReader()) }
            allprojects { project ->
                localProperties.forEach { key, value ->
                    if (!project.hasProperty(key.toString())) {
                        project.extensions.add(key.toString(), value)
                    }
                }
            }
        }
    }
}
